server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # API em outro host: o Angular usa apiUrl absoluto em environment.vps.ts

    location / {
        try_files $uri $uri/ /index.html;
    }
}
